# Generated by Django 5.1.5 on 2026-02-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_testmatch_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='testbot',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
